apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  MONGO_URI: "mongodb://mongodb-0.mongodb-service:27017,mongodb-1.mongodb-service:27017,mongodb-2.mongodb-service:27017/posts?replicaSet=rs0"
  PORT: "3000"